const CREW_TRIPS = [
  {
    "sport": "Soccer",
    "name": "Lexington SA Cup",
    "month": "Febuary",
    "startDate": "1st",
    "endDate": "2nd",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "2",
    "crew": "PJ, TREY GODCHAUX",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Academy World Cup Friendlies",
    "month": "Febuary",
    "startDate": "8th",
    "endDate": "9th",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "1",
    "crew": "TREY GODCHAUX",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "MYSA Spring Shootout",
    "month": "Febuary",
    "startDate": "8th",
    "endDate": "9th",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "2",
    "crew": "PJ, DBLACK",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "2025 Cal North Junior Cup",
    "month": "Febuary",
    "startDate": "15th",
    "endDate": "16th",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "1",
    "crew": "JABARI WOODS",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Icebreaker 2025",
    "month": "Febuary",
    "startDate": "15th",
    "endDate": "17th",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "1",
    "crew": "Will Fox",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Elk Grove Spring Kickoff Classic",
    "month": "Febuary",
    "startDate": "15th",
    "endDate": "16th",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "2",
    "crew": "DBLACK, PJ",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Power Ford Rio Rapids Cup",
    "month": "Febuary",
    "startDate": "15th",
    "endDate": "16th",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "2",
    "crew": "REGGIE, Caden",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Central USSSA",
    "month": "Febuary",
    "startDate": "22nd",
    "endDate": "23rd",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "2",
    "crew": "HUNTER HEBERT, TREY GODCHAUX",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Winter Wind Up Grand Slam",
    "month": "Febuary",
    "startDate": "21st",
    "endDate": "22nd",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "1",
    "crew": "Lane",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "28th Annual Sun belt classic",
    "month": "Febuary",
    "startDate": "22nd",
    "endDate": "23rd",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "2",
    "crew": "WES, TK",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Castro Valley Spring Classic",
    "month": "Febuary",
    "startDate": "22nd",
    "endDate": "23rd",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "3",
    "crew": "DBLACK, PJ, JABARI WOODS",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Shawnee Tournament",
    "month": "Feb",
    "startDate": "28th",
    "endDate": "2nd",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "2",
    "crew": "Will Fox, Trae Callias",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "2025 COPA DE ÁRBOLES",
    "month": "March",
    "startDate": "1st",
    "endDate": "2nd",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "1",
    "crew": "JR",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "BB",
    "name": "March Madness (grand slam)",
    "month": "March",
    "startDate": "1st",
    "endDate": "3rd",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "3",
    "crew": "Caden, RYAN RICHARD",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "East Coast Spring Shootout (VA Rush)",
    "month": "March",
    "startDate": "7th",
    "endDate": "9th",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "1",
    "crew": "Abby",
    "pexCard": "",
    "leaveDate": "3/6/2025",
    "leaveTime": "12:00:00 PM",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Red Stick Tournament",
    "month": "March",
    "startDate": "6th",
    "endDate": "9th",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "2",
    "crew": "PJ, Will Fox",
    "pexCard": "",
    "leaveDate": "3/7/2025",
    "leaveTime": "12:00:00 PM",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "soccer",
    "name": "Copa Surf",
    "month": "March",
    "startDate": "7th",
    "endDate": "9th",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "2",
    "crew": "TK, Chandler",
    "pexCard": "",
    "leaveDate": "3/6/2025",
    "leaveTime": "12:00:00 PM",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Central MS (one day)",
    "month": "March",
    "startDate": "8th",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "1",
    "crew": "JR",
    "pexCard": "",
    "leaveDate": "3/7/2025",
    "leaveTime": "2:00:00 PM",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Springfest 2025",
    "month": "March",
    "startDate": "8th",
    "endDate": "9th",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "1",
    "crew": "Caden",
    "pexCard": "",
    "leaveDate": "3/6/2025",
    "leaveTime": "8:00:00 AM",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "8th Annual Luck O The Irish",
    "month": "March",
    "startDate": "15th",
    "endDate": "16th",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "2",
    "crew": "WES, Emma",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "2:00:00 PM",
    "rentalReturn": "",
    "leaveTimesSent": "Yes",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "CC's Coffee Classic",
    "month": "March",
    "startDate": "15th",
    "endDate": "16th",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "2",
    "crew": "RYAN RICHARD, Will Fox, Chandler",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "12:00:00 PM",
    "rentalReturn": "",
    "leaveTimesSent": "Yes",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Juniors Cup",
    "month": "March",
    "startDate": "15th",
    "endDate": "16th",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "1",
    "crew": "Caden",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "10:00:00 AM",
    "rentalReturn": "",
    "leaveTimesSent": "Yes",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Courtesy Cajun Lagniappe (LA Crew)",
    "month": "March",
    "startDate": "14th",
    "endDate": "16th",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "1",
    "crew": "TREY GODCHAUX, JABARI WOODS",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "pick up friday evening",
    "rentalReturn": "",
    "leaveTimesSent": "Yes",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Polar Cup",
    "month": "March",
    "startDate": "14th",
    "endDate": "15th",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "1",
    "crew": "Trae Callias",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "12:00:00 AM",
    "rentalReturn": "",
    "leaveTimesSent": "Yes",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "BYSC Spring Challenge",
    "month": "March",
    "startDate": "14th",
    "endDate": "15th",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "1",
    "crew": "PJ",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "12:00:00 PM",
    "rentalReturn": "",
    "leaveTimesSent": "Yes",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "One Knox Collective Cup",
    "month": "March",
    "startDate": "14th",
    "endDate": "16th",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "1",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "Yes",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "St. Patrick's Show Down Grand Slam",
    "month": "March",
    "startDate": "14th",
    "endDate": "15th",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "1",
    "crew": "Lane",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "Yes",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Phoenix Cup - Boys",
    "month": "March",
    "startDate": "21st",
    "endDate": "23rd",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "3",
    "crew": "PJ, Trae Callias, Landri",
    "pexCard": "",
    "leaveDate": "Wednesday 8pm",
    "leaveTime": "",
    "rentalReturn": "Monday Evening",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Super Slam - Turf Warz Classic ll",
    "month": "March",
    "startDate": "22nd",
    "endDate": "23rd",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "1",
    "crew": "Lane",
    "pexCard": "",
    "leaveDate": "Friday 12 pm",
    "leaveTime": "",
    "rentalReturn": "Monday Morning",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "baseball",
    "name": "Central MS- Super Slam",
    "month": "March",
    "startDate": "22nd",
    "endDate": "23rd",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "4",
    "crew": "Caden, Chandler, JR, Christopher",
    "pexCard": "",
    "leaveDate": "Friday 12 pm",
    "leaveTime": "",
    "rentalReturn": "Monday Morning",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Spring Turf Fest- Ohio Glaxies",
    "month": "March",
    "startDate": "21st",
    "endDate": "23rd",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "1",
    "crew": "DBLACK",
    "pexCard": "",
    "leaveDate": "Thursday 6 pm",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Vette City Showcase",
    "month": "March",
    "startDate": "21st",
    "endDate": "23rd",
    "status": "LOCKED IN",
    "state": "",
    "crewNeeded": "1",
    "crew": "Will Fox",
    "pexCard": "",
    "leaveDate": "Thursday 6 pm",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Vegas Cup Spring Classic",
    "month": "March",
    "startDate": "28th",
    "endDate": "30th",
    "status": "LOCKED IN",
    "state": "NV",
    "crewNeeded": "2",
    "crew": "PJ, Will Fox",
    "pexCard": "Dblack",
    "leaveDate": "10 am Thurs",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Southeast Shootout",
    "month": "March",
    "startDate": "28th",
    "endDate": "30th",
    "status": "LOCKED IN",
    "state": "LA",
    "crewNeeded": "3",
    "crew": "Grayson, RYAN RICHARD, GARRET",
    "pexCard": "visa 200",
    "leaveDate": "Friday 2 pm",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Kolping Memorial Tournament",
    "month": "March",
    "startDate": "28th",
    "endDate": "30th",
    "status": "LOCKED IN",
    "state": "OH",
    "crewNeeded": "1",
    "crew": "Trae Callias",
    "pexCard": "Justice",
    "leaveDate": "Thursday 6 pm",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "United Spring Turf Challenge",
    "month": "March",
    "startDate": "29th",
    "endDate": "30th",
    "status": "LOCKED IN",
    "state": "OH",
    "crewNeeded": "1",
    "crew": "Landri",
    "pexCard": "Just Rivere",
    "leaveDate": "Thursday 6 pm",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Prep Baseball KC Clash",
    "month": "March",
    "startDate": "28th",
    "endDate": "30th",
    "status": "LOCKED IN",
    "state": "KC",
    "crewNeeded": "1",
    "crew": "TK",
    "pexCard": "TK",
    "leaveDate": "Thursday 6 pm",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Central MS Metro Madness",
    "month": "March",
    "startDate": "28th",
    "endDate": "29th",
    "status": "LOCKED IN",
    "state": "MS",
    "crewNeeded": "2",
    "crew": "Christopher, Cody Lyons",
    "pexCard": "visa 200",
    "leaveDate": "Friday after 12 pm",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "CFCA Chattanooga Cup",
    "month": "March",
    "startDate": "29th",
    "endDate": "30th",
    "status": "LOCKED IN",
    "state": "TN",
    "crewNeeded": "1",
    "crew": "MICHAEL FLASH",
    "pexCard": "visa 400",
    "leaveDate": "Thursday 6 pm",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "GMB Rawlings Championship",
    "month": "March",
    "startDate": "28th",
    "endDate": "30th",
    "status": "LOCKED IN",
    "state": "TN",
    "crewNeeded": "1",
    "crew": "CARTER WILLIAMS",
    "pexCard": "visa 400",
    "leaveDate": "Thursday 8 pm",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "PSG Academy Cup",
    "month": "March",
    "startDate": "28th",
    "endDate": "30th",
    "status": "LOCKED IN",
    "state": "AZ",
    "crewNeeded": "1-2",
    "crew": "Chandler, Hudson",
    "pexCard": "Reggie",
    "leaveDate": "Thursday 8 am",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Bayou Shootout",
    "month": "April",
    "startDate": "5th",
    "endDate": "6th",
    "status": "LOCKED IN",
    "state": "LA",
    "crewNeeded": "2",
    "crew": "Maddox, DBLACK",
    "pexCard": "landri",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Pensacola Classic",
    "month": "April",
    "startDate": "4th",
    "endDate": "6th",
    "status": "LOCKED IN",
    "state": "FL",
    "crewNeeded": "1",
    "crew": "PJ",
    "pexCard": "JR",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "KC Super Select",
    "month": "April",
    "startDate": "4th",
    "endDate": "6th",
    "status": "LOCKED IN",
    "state": "MO",
    "crewNeeded": "1",
    "crew": "Will Fox",
    "pexCard": "will",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Spring Fling Tournament",
    "month": "April",
    "startDate": "4th",
    "endDate": "6th",
    "status": "LOCKED IN",
    "state": "OK",
    "crewNeeded": "1",
    "crew": "TK",
    "pexCard": "TK",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Madison 56ers Spring Cup",
    "month": "April",
    "startDate": "5th",
    "endDate": "6th",
    "status": "LOCKED IN",
    "state": "WI",
    "crewNeeded": "1",
    "crew": "CARTER WILLIAMS",
    "pexCard": "DBLACK",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Puri Cup College Showcase 2025",
    "month": "April",
    "startDate": "4th",
    "endDate": "6th",
    "status": "LOCKED IN",
    "state": "IL",
    "crewNeeded": "1",
    "crew": "Caden",
    "pexCard": "REGGIE",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "2025 GMB King of Rings",
    "month": "April",
    "startDate": "5th",
    "endDate": "6th",
    "status": "LOCKED IN",
    "state": "TN",
    "crewNeeded": "1",
    "crew": "Hudson",
    "pexCard": "Justice",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Central MS. Kingz of Swing Southeast Showcase",
    "month": "April",
    "startDate": "5th",
    "endDate": "6th",
    "status": "LOCKED IN",
    "state": "MS",
    "crewNeeded": "3",
    "crew": "Austin, Cody Lyons, TREY GODCHAUX",
    "pexCard": "Lane",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Central MS Magnolia State Classic",
    "month": "April",
    "startDate": "5th",
    "endDate": "6th",
    "status": "LOCKED IN",
    "state": "MS",
    "crewNeeded": "1",
    "crew": "Cooper David",
    "pexCard": "trae",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Twin City Slugfest",
    "month": "April",
    "startDate": "5th",
    "endDate": "6th",
    "status": "LOCKED IN",
    "state": "LA",
    "crewNeeded": "1",
    "crew": "Chandler",
    "pexCard": "Ryan",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Miss. Soccer Association (Key City)",
    "month": "April",
    "startDate": "11th",
    "endDate": "12th",
    "status": "LOCKED IN",
    "state": "MS",
    "crewNeeded": "1",
    "crew": "Chandler",
    "pexCard": "lane",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "NC Rush Triad Beat the Heat (NC Triad)",
    "month": "April",
    "startDate": "11th",
    "endDate": "13th",
    "status": "LOCKED IN",
    "state": "NC",
    "crewNeeded": "2",
    "crew": "Maddox, CARTER WILLIAMS",
    "pexCard": "ryan",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Puri Champions Cup",
    "month": "April",
    "startDate": "11th",
    "endDate": "14th",
    "status": "LOCKED IN",
    "state": "IL",
    "crewNeeded": "2",
    "crew": "PJ",
    "pexCard": "pj",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "KC Showdown",
    "month": "April",
    "startDate": "11th",
    "endDate": "13th",
    "status": "LOCKED IN",
    "state": "MO",
    "crewNeeded": "1",
    "crew": "Bryce Cousin",
    "pexCard": "dblack",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Gulfport Spring Championship",
    "month": "April",
    "startDate": "12th",
    "endDate": "13th",
    "status": "LOCKED IN",
    "state": "MS",
    "crewNeeded": "1",
    "crew": "Will Fox",
    "pexCard": "will",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Central MS. Super Slam #2",
    "month": "April",
    "startDate": "11th",
    "endDate": "13th",
    "status": "LOCKED IN",
    "state": "MS",
    "crewNeeded": "3-4",
    "crew": "Hudson, CHRIS PEYTON, Ross Bertrand, Cody Lyons",
    "pexCard": "jr",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "West Fel Turf Battle",
    "month": "April",
    "startDate": "12th",
    "endDate": "13th",
    "status": "LOCKED IN",
    "state": "LA",
    "crewNeeded": "1",
    "crew": "HUNTER HEBERT",
    "pexCard": "tk",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Texas Easter Cup",
    "month": "April",
    "startDate": "19th",
    "endDate": "20th",
    "status": "LOCKED IN",
    "state": "TX",
    "crewNeeded": "1",
    "crew": "TK, Landri",
    "pexCard": "TK",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "East Valley Spring Invitational 2025",
    "month": "April",
    "startDate": "14th",
    "endDate": "19th",
    "status": "LOCKED IN",
    "state": "AZ",
    "crewNeeded": "3",
    "crew": "Chandler, Hudson",
    "pexCard": "CHANDLER",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "2025 Easter Cup",
    "month": "",
    "startDate": "",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "TX",
    "crewNeeded": "1",
    "crew": "Austin",
    "pexCard": "ryan richard",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Central MS Bunnyball (One Day)",
    "month": "April",
    "startDate": "19th",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "MS",
    "crewNeeded": "2",
    "crew": "PJ",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Central MS Easter Eggtravaganza (One Day)",
    "month": "April",
    "startDate": "19th",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "MS",
    "crewNeeded": "1",
    "crew": "Nelson, CHRIS PEYTON",
    "pexCard": "PJ",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Easter Bracket Buster",
    "month": "April",
    "startDate": "18th",
    "endDate": "19th",
    "status": "LOCKED IN",
    "state": "MO",
    "crewNeeded": "1",
    "crew": "Maddox",
    "pexCard": "MADDOX",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Easter Bunny Bash (One Day)",
    "month": "April",
    "startDate": "19th",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "AR",
    "crewNeeded": "1",
    "crew": "Bryce Cousin",
    "pexCard": "JR",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "South MS Easter Bash (One day) Columbia",
    "month": "April",
    "startDate": "19th",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "MS",
    "crewNeeded": "1",
    "crew": "MICHAEL FLASH",
    "pexCard": "MIKE FLASH",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "South MS Easter Bash (One day) Petal",
    "month": "April",
    "startDate": "19th",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "MS",
    "crewNeeded": "1",
    "crew": "CARTER WILLIAMS",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "39TH Annual PVSC Spring Classic 2025",
    "month": "April",
    "startDate": "24th",
    "endDate": "27th",
    "status": "LOCKED IN",
    "state": "ID",
    "crewNeeded": "2",
    "crew": "JADEN GUIDRY, Landri",
    "pexCard": "landri",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Wisconsin Spring Classic",
    "month": "April",
    "startDate": "26th",
    "endDate": "27th",
    "status": "LOCKED IN",
    "state": "WI",
    "crewNeeded": "2",
    "crew": "Kennedy Livings, Cullen Champagn",
    "pexCard": "dblack",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Capital Classic",
    "month": "April",
    "startDate": "26th",
    "endDate": "27th",
    "status": "LOCKED IN",
    "state": "MN",
    "crewNeeded": "2",
    "crew": "Chandler, vernon",
    "pexCard": "Chandler",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Quad City Spring Shootout",
    "month": "April",
    "startDate": "25th",
    "endDate": "27th",
    "status": "LOCKED IN",
    "state": "IL",
    "crewNeeded": "1",
    "crew": "Caden",
    "pexCard": "Caden",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Capital City Cup",
    "month": "April",
    "startDate": "26th",
    "endDate": "27th",
    "status": "LOCKED IN",
    "state": "NE",
    "crewNeeded": "1",
    "crew": "PJ",
    "pexCard": "PJ",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "South MS Touch Em All",
    "month": "April",
    "startDate": "26th",
    "endDate": "27th",
    "status": "LOCKED IN",
    "state": "MS",
    "crewNeeded": "1",
    "crew": "Will Fox",
    "pexCard": "Will",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Central MS Doubles and Dingers",
    "month": "April",
    "startDate": "25th",
    "endDate": "27th",
    "status": "LOCKED IN",
    "state": "MS",
    "crewNeeded": "3",
    "crew": "MICHAEL FLASH, CHRIS PEYTON, Austin",
    "pexCard": "Flash",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Days of Thunder Grand Slam",
    "month": "April",
    "startDate": "26th",
    "endDate": "27th",
    "status": "LOCKED IN",
    "state": "IN",
    "crewNeeded": "2",
    "crew": "HUNTER HEBERT, Makhail Hilliard",
    "pexCard": "Justin",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Pride of the Fox Turf Classic",
    "month": "April",
    "startDate": "25th",
    "endDate": "27th",
    "status": "LOCKED IN",
    "state": "IL",
    "crewNeeded": "1",
    "crew": "CLARK CHILDS",
    "pexCard": "Lane",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Deep South Super Regional",
    "month": "April",
    "startDate": "26th",
    "endDate": "27th",
    "status": "LOCKED IN",
    "state": "LA",
    "crewNeeded": "4",
    "crew": "Bryce Cousin, RYAN RICHARD, SILAS DEVILLE, Carter Kramer",
    "pexCard": "Ryan",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Dugout Derby",
    "month": "April",
    "startDate": "26th",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "AR",
    "crewNeeded": "1",
    "crew": "Cody Lyons",
    "pexCard": "Nelson",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "2025 Spring Invite",
    "month": "May",
    "startDate": "2nd",
    "endDate": "4th",
    "status": "LOCKED IN",
    "state": "IL",
    "crewNeeded": "2",
    "crew": "Will Fox",
    "pexCard": "Will",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Epic Cup",
    "month": "May",
    "startDate": "3rd",
    "endDate": "4th",
    "status": "LOCKED IN",
    "state": "KY",
    "crewNeeded": "2",
    "crew": "Austin",
    "pexCard": "Carter",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Davis Legacy Spring Super Classico",
    "month": "May",
    "startDate": "3rd",
    "endDate": "4th",
    "status": "LOCKED IN",
    "state": "CA",
    "crewNeeded": "1",
    "crew": "Lane",
    "pexCard": "Amex",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Spring Classic",
    "month": "May",
    "startDate": "2nd",
    "endDate": "4th",
    "status": "LOCKED IN",
    "state": "IL",
    "crewNeeded": "1",
    "crew": "PJ",
    "pexCard": "PJ",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Norski Spring Fling Tournament",
    "month": "May",
    "startDate": "2nd",
    "endDate": "4th",
    "status": "LOCKED IN",
    "state": "WI",
    "crewNeeded": "1",
    "crew": "Chandler",
    "pexCard": "Chandler",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Freedom Cup Tournament FSL",
    "month": "May",
    "startDate": "2nd",
    "endDate": "4th",
    "status": "LOCKED IN",
    "state": "NJ",
    "crewNeeded": "2",
    "crew": "Caden, CLARK CHILDS",
    "pexCard": "Caden",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Bling Bling Gold Chain Event AR",
    "month": "May",
    "startDate": "3rd",
    "endDate": "4th",
    "status": "LOCKED IN",
    "state": "AR",
    "crewNeeded": "1",
    "crew": "Nelson",
    "pexCard": "Nelson",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Cinco De Mayo Slugfest 2D",
    "month": "May",
    "startDate": "3rd",
    "endDate": "4th",
    "status": "LOCKED IN",
    "state": "LA",
    "crewNeeded": "2",
    "crew": "RYAN RICHARD, Ross Bertrand",
    "pexCard": "Ryan",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "South MS- Cinco De Mayo Showdown",
    "month": "May",
    "startDate": "3rd",
    "endDate": "4th",
    "status": "LOCKED IN",
    "state": "MS",
    "crewNeeded": "2",
    "crew": "CHRIS PEYTON, MICHAEL FLASH",
    "pexCard": "Michael",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Central MS Turf a Mania",
    "month": "May",
    "startDate": "3rd",
    "endDate": "4th",
    "status": "LOCKED IN",
    "state": "MS",
    "crewNeeded": "2",
    "crew": "Hudson, JADEN GUIDRY",
    "pexCard": "Lane",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Cinco De Mayo @ gardendale",
    "month": "May",
    "startDate": "3rd",
    "endDate": "4th",
    "status": "LOCKED IN",
    "state": "AL",
    "crewNeeded": "2",
    "crew": "CARTER WILLIAMS, Maddox",
    "pexCard": "Maddox",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "May the 4th be With you",
    "month": "May",
    "startDate": "3rd",
    "endDate": "4th",
    "status": "LOCKED IN",
    "state": "AL",
    "crewNeeded": "2",
    "crew": "TREY GODCHAUX",
    "pexCard": "JR",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "MSA Key City",
    "month": "May",
    "startDate": "10th",
    "endDate": "11th",
    "status": "LOCKED IN",
    "state": "MS",
    "crewNeeded": "1",
    "crew": "Chandler",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "YMS Epic Tournament",
    "month": "May",
    "startDate": "10th",
    "endDate": "11th",
    "status": "LOCKED IN",
    "state": "PA",
    "crewNeeded": "2",
    "crew": "PJ, TK",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Dallas Spring Showcase",
    "month": "May",
    "startDate": "9th",
    "endDate": "11th",
    "status": "LOCKED IN",
    "state": "TX",
    "crewNeeded": "2",
    "crew": "CARTER WILLIAMS, Maddox",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "USSSA AL Athens",
    "month": "May",
    "startDate": "10th",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "AL",
    "crewNeeded": "1",
    "crew": "CLARK CHILDS",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "USSSA AL Vestavia",
    "month": "May",
    "startDate": "10th",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "AL",
    "crewNeeded": "2",
    "crew": "Landri, Ottis Chew",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Mother's Day Bash 2D",
    "month": "May",
    "startDate": "10th",
    "endDate": "11th",
    "status": "LOCKED IN",
    "state": "LA",
    "crewNeeded": "2",
    "crew": "Caden, HUNTER HEBERT",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Mother's Day - Grand Slam Sports (one day)",
    "month": "May",
    "startDate": "10th",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "AL",
    "crewNeeded": "2",
    "crew": "BEAUX CREEL, Stephen Henry",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Central MS Moms Rock (One Day)",
    "month": "May",
    "startDate": "10th",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "MS",
    "crewNeeded": "2",
    "crew": "MANUEL, Kennedy Livings",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Mother's Day Classic VI 2D",
    "month": "May",
    "startDate": "10th",
    "endDate": "11th",
    "status": "LOCKED IN",
    "state": "LA",
    "crewNeeded": "2",
    "crew": "Grayson, Will Fox, Ross Bertrand, Deuce",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Grand Slam Mother Knows Best",
    "month": "May",
    "startDate": "10th",
    "endDate": "11th",
    "status": "LOCKED IN",
    "state": "IN",
    "crewNeeded": "2",
    "crew": "Hudson, CODY MEYERS",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Mother's Day Mayhem Grand Slam",
    "month": "May",
    "startDate": "9th",
    "endDate": "10th",
    "status": "LOCKED IN",
    "state": "LA",
    "crewNeeded": "1",
    "crew": "MICHAEL FLASH",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Rocky Mtn. Spring Championship",
    "month": "May",
    "startDate": "16th",
    "endDate": "18th",
    "status": "LOCKED IN",
    "state": "CO",
    "crewNeeded": "2",
    "crew": "Ottis Chew, JADEN GUIDRY",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Copa De Sturgis",
    "month": "May",
    "startDate": "16th",
    "endDate": "18th",
    "status": "UNASSIGNED",
    "state": "SD",
    "crewNeeded": "1",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Mckinney Spring Cup",
    "month": "May",
    "startDate": "16th",
    "endDate": "18th",
    "status": "LOCKED IN",
    "state": "TX",
    "crewNeeded": "2",
    "crew": "Hudson, TK",
    "pexCard": "",
    "leaveDate": "3/4/2025",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Next Generation Cup",
    "month": "May",
    "startDate": "15th",
    "endDate": "18th",
    "status": "LOCKED IN",
    "state": "TX",
    "crewNeeded": "2",
    "crew": "PJ, Trae Callias",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Golden State Challenge",
    "month": "May",
    "startDate": "17th",
    "endDate": "18th",
    "status": "LOCKED IN",
    "state": "CA",
    "crewNeeded": "1",
    "crew": "CARTER WILLIAMS",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Xtreme Cup 2025",
    "month": "May",
    "startDate": "17th",
    "endDate": "18th",
    "status": "LOCKED IN",
    "state": "GA",
    "crewNeeded": "2",
    "crew": "Caden, CODY MEYERS",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Nomads Spring Showdown",
    "month": "May",
    "startDate": "17th",
    "endDate": "18th",
    "status": "LOCKED IN",
    "state": "CA",
    "crewNeeded": "1",
    "crew": "Ethan Busby",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Rec Round Up",
    "month": "May",
    "startDate": "17th",
    "endDate": "18th",
    "status": "LOCKED IN",
    "state": "GA",
    "crewNeeded": "1",
    "crew": "JUSTICE HYMEL",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "May Day Mayhem Classic",
    "month": "May",
    "startDate": "16th",
    "endDate": "18th",
    "status": "LOCKED IN",
    "state": "PA",
    "crewNeeded": "1",
    "crew": "Ross Bertrand, BEAUX CREEL",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Deep South AA Festival",
    "month": "May",
    "startDate": "17th",
    "endDate": "18th",
    "status": "LOCKED IN",
    "state": "LA",
    "crewNeeded": "2",
    "crew": "Cullen Champagn, Will Fox, FABIAN ANDRUS",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Central MS. Boys of Summer",
    "month": "May",
    "startDate": "16th",
    "endDate": "18th",
    "status": "LOCKED IN",
    "state": "MS",
    "crewNeeded": "4",
    "crew": "Cody Lyons, CHRIS PEYTON, Chase, D'Atric",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "I-20 Summer Invitational Tournament",
    "month": "May",
    "startDate": "17th",
    "endDate": "18th",
    "status": "LOCKED IN",
    "state": "LA",
    "crewNeeded": "1",
    "crew": "TREY GODCHAUX",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Catch ME IF YOU CAN",
    "month": "May",
    "startDate": "17th",
    "endDate": "18th",
    "status": "LOCKED IN",
    "state": "AL",
    "crewNeeded": "2",
    "crew": "Maddox, JoJo Breeland",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Bossier Ship featuring Lathan the Kid Umpire",
    "month": "May",
    "startDate": "17th",
    "endDate": "18th",
    "status": "LOCKED IN",
    "state": "LA",
    "crewNeeded": "1",
    "crew": "Deuce",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Grand Slame Weather The Storm",
    "month": "May",
    "startDate": "17th",
    "endDate": "18th",
    "status": "UNASSIGNED",
    "state": "IN",
    "crewNeeded": "2",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Freedom Games (SAT ONLY)",
    "month": "",
    "startDate": "24th",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "IN",
    "crewNeeded": "2",
    "crew": "Diantre Sam, vernon",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "(Sat) Honor The Game @ Albertville",
    "month": "May",
    "startDate": "24th",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "AL",
    "crewNeeded": "1",
    "crew": "Bryce Cousin",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "(SAT) Honor The Game @ Lincoln",
    "month": "May",
    "startDate": "24th",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "AL",
    "crewNeeded": "1",
    "crew": "Bennet Derouen, Damon Thompson, Landri",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "GMB Memorial Day Classic- Music City",
    "month": "May",
    "startDate": "23rd",
    "endDate": "25th",
    "status": "LOCKED IN",
    "state": "TN",
    "crewNeeded": "1",
    "crew": "Chandler",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Central MS Stars and Strikes(One Day)",
    "month": "May",
    "startDate": "24th",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "MS",
    "crewNeeded": "2",
    "crew": "Ottis Chew, WAG",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Central MS Stars and Strikes(One Day)",
    "month": "May",
    "startDate": "24th",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "MS",
    "crewNeeded": "1",
    "crew": "JoJo Breeland",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "South MS- Stars, Stripes, Strikes",
    "month": "May",
    "startDate": "24th",
    "endDate": "25th",
    "status": "LOCKED IN",
    "state": "MS",
    "crewNeeded": "1",
    "crew": "Ross Bertrand",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "2025 Virginian Elite Soccer Tournament",
    "month": "May",
    "startDate": "23RD",
    "endDate": "25th",
    "status": "LOCKED IN",
    "state": "VA",
    "crewNeeded": "4",
    "crew": "Maddox, CARTER WILLIAMS, Ethan Busby, MICHAEL FLASH",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Vegas Memorial Cup",
    "month": "May",
    "startDate": "23rd",
    "endDate": "26th",
    "status": "LOCKED IN",
    "state": "NV",
    "crewNeeded": "2",
    "crew": "PJ, Will Fox",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Liberty Cup Youth Soccer Festival",
    "month": "May",
    "startDate": "23rd",
    "endDate": "25th",
    "status": "LOCKED IN",
    "state": "IL",
    "crewNeeded": "2",
    "crew": "JUSTICE HYMEL, CHRIS PEYTON",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Ralph Downey Memorial Day Classic",
    "month": "May",
    "startDate": "24th",
    "endDate": "25th",
    "status": "LOCKED IN",
    "state": "VA",
    "crewNeeded": "1",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Eli7e Cup",
    "month": "May",
    "startDate": "24th",
    "endDate": "25th",
    "status": "LOCKED IN",
    "state": "CA",
    "crewNeeded": "1",
    "crew": "Cody Lyons",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "NewPort Mesa Cup",
    "month": "May",
    "startDate": "24th",
    "endDate": "25th",
    "status": "LOCKED IN",
    "state": "CA",
    "crewNeeded": "2",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Tournament of Champions",
    "month": "May",
    "startDate": "24th",
    "endDate": "25th",
    "status": "LOCKED IN",
    "state": "CA",
    "crewNeeded": "1",
    "crew": "Hudson",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Memorial Day 5v5 Tournament",
    "month": "May",
    "startDate": "26th",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "GA",
    "crewNeeded": "1",
    "crew": "Caleb Alexander",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "(Sat-Sun) AA Diamond Cup State Tournament",
    "month": "May",
    "startDate": "31st",
    "endDate": "1st",
    "status": "LOCKED IN",
    "state": "AL",
    "crewNeeded": "3",
    "crew": "JUSTICE HYMEL, BEAUX CREEL, William Gary",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Alabama State Tournament",
    "month": "May",
    "startDate": "31st",
    "endDate": "1st",
    "status": "LOCKED IN",
    "state": "AL",
    "crewNeeded": "4",
    "crew": "CARTER WILLIAMS, Maddox, Stephen Henry, COLE MATHRENE",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "AL Cullman One Day",
    "month": "May",
    "startDate": "31st",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "AL",
    "crewNeeded": "2",
    "crew": "SILAS DEVILLE, Carter Kramer",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Central MS Triple Play Sports Championships",
    "month": "May",
    "startDate": "31st",
    "endDate": "1st",
    "status": "LOCKED IN",
    "state": "MS",
    "crewNeeded": "1",
    "crew": "Damon Thompson",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "South MS- Oak Grove Sat Only",
    "month": "May",
    "startDate": "31st",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "MS",
    "crewNeeded": "1",
    "crew": "WAG",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "South MS State Warm Up",
    "month": "May",
    "startDate": "31st",
    "endDate": "1st",
    "status": "UNASSIGNED",
    "state": "MS",
    "crewNeeded": "",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "MP3 Series - South LA State Champ",
    "month": "May",
    "startDate": "31st",
    "endDate": "1st",
    "status": "LOCKED IN",
    "state": "LA",
    "crewNeeded": "2",
    "crew": "Austin, JADEN GUIDRY",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Grand Slame KY State Tourney",
    "month": "May",
    "startDate": "31st",
    "endDate": "1st",
    "status": "LOCKED IN",
    "state": "IN",
    "crewNeeded": "2",
    "crew": "Ross Bertrand, JoJo Breeland",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Baton Rouge AA Summer Championship",
    "month": "May",
    "startDate": "31st",
    "endDate": "1st",
    "status": "LOCKED IN",
    "state": "LA",
    "crewNeeded": "2",
    "crew": "Chandler Dew, LANE MONTGOMERY",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Select Series Championship 2D",
    "month": "May",
    "startDate": "31st",
    "endDate": "1st",
    "status": "LOCKED IN",
    "state": "LA",
    "crewNeeded": "2",
    "crew": "CLARK CHILDS, Ben Landgrave",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Bring the Heat One Day",
    "month": "May",
    "startDate": "31st",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "AR",
    "crewNeeded": "1",
    "crew": "Cullen Champagn",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Bring the Heat Marion",
    "month": "May",
    "startDate": "31st",
    "endDate": "1st",
    "status": "LOCKED IN",
    "state": "AR",
    "crewNeeded": "1",
    "crew": "Marquis Dangerfield",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "North LA State Championship",
    "month": "May",
    "startDate": "31st",
    "endDate": "1st",
    "status": "LOCKED IN",
    "state": "LA",
    "crewNeeded": "1",
    "crew": "Cody Lyons",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "2025 GMB Bucket Bash – Music City",
    "month": "May",
    "startDate": "30th",
    "endDate": "1st",
    "status": "LOCKED IN",
    "state": "TN",
    "crewNeeded": "1",
    "crew": "Hudson",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Patriots Cup",
    "month": "May",
    "startDate": "31st",
    "endDate": "1st",
    "status": "LOCKED IN",
    "state": "CA",
    "crewNeeded": "1",
    "crew": "CHRIS PEYTON",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Airpitch Tournament",
    "month": "May",
    "startDate": "31st",
    "endDate": "1st",
    "status": "LOCKED IN",
    "state": "TX",
    "crewNeeded": "1",
    "crew": "RYAN RICHARD",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "The California Super Cup",
    "month": "May",
    "startDate": "31st",
    "endDate": "1st",
    "status": "LOCKED IN",
    "state": "CA",
    "crewNeeded": "1",
    "crew": "Ethan Busby",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "St. Croix Cup",
    "month": "May",
    "startDate": "31st",
    "endDate": "1st",
    "status": "LOCKED IN",
    "state": "MN",
    "crewNeeded": "1",
    "crew": "PJ",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "City of Champions",
    "month": "May",
    "startDate": "30th",
    "endDate": "1st",
    "status": "LOCKED IN",
    "state": "TX",
    "crewNeeded": "1",
    "crew": "MANUEL",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "High Peaks Cup",
    "month": "May",
    "startDate": "31st",
    "endDate": "1st",
    "status": "LOCKED IN",
    "state": "NY",
    "crewNeeded": "1",
    "crew": "Will Fox",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Wolves Spring Cup",
    "month": "May",
    "startDate": "31st",
    "endDate": "1st",
    "status": "LOCKED IN",
    "state": "NE",
    "crewNeeded": "1",
    "crew": "Caden",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "2025 Sunburst Tournament",
    "month": "MAY",
    "startDate": "31st",
    "endDate": "1st",
    "status": "LOCKED IN",
    "state": "PA",
    "crewNeeded": "2",
    "crew": "Chandler, Bryce Cousin",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Kelvin Norman & Mile High Showcase",
    "month": "June",
    "startDate": "6th",
    "endDate": "8th",
    "status": "LOCKED IN",
    "state": "CO",
    "crewNeeded": "2",
    "crew": "JUSTICE HYMEL, Grayson",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Scheels Rushmore Cup",
    "month": "JUNE",
    "startDate": "7th",
    "endDate": "8th",
    "status": "LOCKED IN",
    "state": "SD",
    "crewNeeded": "1",
    "crew": "TK",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "MT State Cup",
    "month": "JUNE",
    "startDate": "6th",
    "endDate": "8th",
    "status": "LOCKED IN",
    "state": "MT",
    "crewNeeded": "1",
    "crew": "JR",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Eau Claire United",
    "month": "JUNE",
    "startDate": "6th",
    "endDate": "8th",
    "status": "LOCKED IN",
    "state": "IL",
    "crewNeeded": "1",
    "crew": "Maddox, CARTER WILLIAMS",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "2nd Annual Fox Chase Cancer Center Soccer Shootout",
    "month": "JUNE",
    "startDate": "7th",
    "endDate": "8th",
    "status": "LOCKED IN",
    "state": "PA",
    "crewNeeded": "1",
    "crew": "Ross Bertrand",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "2025 Westside Invitational",
    "month": "JUNE",
    "startDate": "6th",
    "endDate": "8th",
    "status": "LOCKED IN",
    "state": "NY",
    "crewNeeded": "2",
    "crew": "Cody Lyons, CHRIS PEYTON",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "2025 LVYSL Tournament",
    "month": "June",
    "startDate": "7th",
    "endDate": "8th",
    "status": "LOCKED IN",
    "state": "PA",
    "crewNeeded": "1",
    "crew": "Chandler Kesler",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Director's Cup",
    "month": "June",
    "startDate": "5th",
    "endDate": "8th",
    "status": "LOCKED IN",
    "state": "IA",
    "crewNeeded": "1",
    "crew": "Will Fox",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Virginia State Tournement",
    "month": "June",
    "startDate": "7th",
    "endDate": "8th",
    "status": "LOCKED IN",
    "state": "VA",
    "crewNeeded": "1",
    "crew": "Cullen Champagn",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "(Sat) Global AA-A State Tournament @Cullman",
    "month": "JUNE",
    "startDate": "7th",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "AL",
    "crewNeeded": "3",
    "crew": "Caleb Alexander, Chandler Dew, Ben Landgrave",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "TSB Beat the Heat",
    "month": "JUNE",
    "startDate": "7th",
    "endDate": "8th",
    "status": "LOCKED IN",
    "state": "TX",
    "crewNeeded": "3",
    "crew": "Josh Laporte, RYAN RICHARD, Marquis Dangerfield",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "SE World Series Warm Up",
    "month": "JUNE",
    "startDate": "7th",
    "endDate": "8th",
    "status": "LOCKED IN",
    "state": "LA",
    "crewNeeded": "2",
    "crew": "MEATBALL, De'adrick",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "USSA AL Global AA State Tournament @ Chelsea",
    "month": "JUNE",
    "startDate": "7th",
    "endDate": "8th",
    "status": "LOCKED IN",
    "state": "AL",
    "crewNeeded": "2",
    "crew": "COLE MATHRENE, Nelson",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "The G.O.A.T.",
    "month": "JUNE",
    "startDate": "6th",
    "endDate": "8th",
    "status": "LOCKED IN",
    "state": "MO",
    "crewNeeded": "2",
    "crew": "JoJo Breeland, Chase Butler",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Grand Slam school's out for summer",
    "month": "JUNE",
    "startDate": "7th",
    "endDate": "8th",
    "status": "LOCKED IN",
    "state": "IN",
    "crewNeeded": "2",
    "crew": "Bennet Derouen, William Gary",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "PBT World Series",
    "month": "JUNE",
    "startDate": "4th",
    "endDate": "8th",
    "status": "LOCKED IN",
    "state": "IN",
    "crewNeeded": "2",
    "crew": "Hudson, BEAUX CREEL",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Hometown Heroes Classic",
    "month": "JUNE",
    "startDate": "6th",
    "endDate": "8th",
    "status": "LOCKED IN",
    "state": "IL",
    "crewNeeded": "2",
    "crew": "Bryce Cousin, Tyler Collins",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Kingpin Classic",
    "month": "June",
    "startDate": "6th",
    "endDate": "8th",
    "status": "UNASSIGNED",
    "state": "PA",
    "crewNeeded": "2",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Section 10 Cup",
    "month": "June",
    "startDate": "14th",
    "endDate": "15th",
    "status": "LOCKED IN",
    "state": "CA",
    "crewNeeded": "1",
    "crew": "De'adrick",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Yellowstone Cup",
    "month": "JUNE",
    "startDate": "12th",
    "endDate": "14th",
    "status": "LOCKED IN",
    "state": "IA",
    "crewNeeded": "3",
    "crew": "Maddox, CARTER WILLIAMS, Eli Alviso",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Lakeville Father's Day Cup",
    "month": "JUNE",
    "startDate": "13th",
    "endDate": "15th",
    "status": "LOCKED IN",
    "state": "MN",
    "crewNeeded": "2",
    "crew": "JoJo Breeland, JUSTICE HYMEL",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "15th Annual Swallows Cup",
    "month": "June",
    "startDate": "14th",
    "endDate": "15th",
    "status": "LOCKED IN",
    "state": "CA",
    "crewNeeded": "2",
    "crew": "PJ, Trae Callias",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Mid Atlantic Cup",
    "month": "June",
    "startDate": "13th",
    "endDate": "15th",
    "status": "LOCKED IN",
    "state": "MA",
    "crewNeeded": "3",
    "crew": "Caleb Alexander, Aubri",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Youth World Series - Tennessee",
    "month": "JUNE",
    "startDate": "11th",
    "endDate": "15th",
    "status": "LOCKED IN",
    "state": "TN",
    "crewNeeded": "2",
    "crew": "Hudson, Will Fox",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "TBS - Myrtle Beach",
    "month": "JUNE",
    "startDate": "10th",
    "endDate": "15th",
    "status": "LOCKED IN",
    "state": "SC",
    "crewNeeded": "2",
    "crew": "CHRIS PEYTON, Bennet Derouen",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "AL State Games",
    "month": "June",
    "startDate": "14th",
    "endDate": "15th",
    "status": "LOCKED IN",
    "state": "AL",
    "crewNeeded": "1",
    "crew": "JR",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "King of the Natural State- Sat ONLY",
    "month": "June",
    "startDate": "14th",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "AR",
    "crewNeeded": "1",
    "crew": "Bryce Cousin",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "DADS' DAY DUEL CLASSIC",
    "month": "June",
    "startDate": "13th",
    "endDate": "15th",
    "status": "LOCKED IN",
    "state": "PA",
    "crewNeeded": "2",
    "crew": "Chase Butler, Tyler Collins",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "(SAT) Arrowhead World Series Warm Up @ Gadson",
    "month": "JUNE",
    "startDate": "14th",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "AL",
    "crewNeeded": "1",
    "crew": "Landon Baptiste",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "(SAT) Arrowhead Wold Series Warm Up @ Cullman",
    "month": "JUNE",
    "startDate": "14th",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "AL",
    "crewNeeded": "2",
    "crew": "Austin, Stephen Henry",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "2025 GMB Fathers Day Classic",
    "month": "JUNE",
    "startDate": "13th",
    "endDate": "15th",
    "status": "LOCKED IN",
    "state": "TN",
    "crewNeeded": "1",
    "crew": "Marquis Dangerfield",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Grand Slam Hey Batter Batter (2, 1 day events)",
    "month": "JUNE",
    "startDate": "14th",
    "endDate": "15th",
    "status": "LOCKED IN",
    "state": "IN",
    "crewNeeded": "2",
    "crew": "Ben Landgrave, Ross Bertrand",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "South MS Rumble in Columbia",
    "month": "JUNE",
    "startDate": "14th",
    "endDate": "15th",
    "status": "LOCKED IN",
    "state": "MS",
    "crewNeeded": "1",
    "crew": "MEATBALL",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "AJ Jones Father’s Day Showstopper",
    "month": "June",
    "startDate": "14th",
    "endDate": "15th",
    "status": "LOCKED IN",
    "state": "IL",
    "crewNeeded": "2",
    "crew": "BEAUX CREEL, Ethan Busby",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Toms River Surf and Turf Summer Classic",
    "month": "June",
    "startDate": "20th",
    "endDate": "22nd",
    "status": "LOCKED IN",
    "state": "NJ",
    "crewNeeded": "1-2",
    "crew": "Ottis Chew",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Nomads Summer Invitational",
    "month": "JUNE",
    "startDate": "21st",
    "endDate": "22nd",
    "status": "LOCKED IN",
    "state": "CA",
    "crewNeeded": "2",
    "crew": "Austin, Marquis Dangerfield",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "2025 Plymouth Youth Soccer Jamboree",
    "month": "JUNE",
    "startDate": "21st",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "MA",
    "crewNeeded": "1",
    "crew": "JR",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Rise Classic",
    "month": "JUNE",
    "startDate": "21st",
    "endDate": "22nd",
    "status": "LOCKED IN",
    "state": "CA",
    "crewNeeded": "1",
    "crew": "Caden",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "5v5 Perryville Under the Lights (Sat Only)",
    "month": "JUNE",
    "startDate": "21st",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "MD",
    "crewNeeded": "1",
    "crew": "Damon Thompson",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Forney Education Foundation Soccer Tournament",
    "month": "June",
    "startDate": "21st",
    "endDate": "",
    "status": "LOCKED IN",
    "state": "TX",
    "crewNeeded": "",
    "crew": "MANUEL",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "Volcano International Soccer Tournament",
    "month": "JUNE",
    "startDate": "20th",
    "endDate": "22nd",
    "status": "LOCKED IN",
    "state": "Hawaii",
    "crewNeeded": "1",
    "crew": "Lane",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "TSB MIDSUMMER CLASH",
    "month": "JUNE",
    "startDate": "21st",
    "endDate": "22nd",
    "status": "LOCKED IN",
    "state": "TX",
    "crewNeeded": "1",
    "crew": "Grayson",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Battle at the Bridge Classic",
    "month": "JUNE",
    "startDate": "20th",
    "endDate": "22nd",
    "status": "LOCKED IN",
    "state": "PA",
    "crewNeeded": "2",
    "crew": "Ben Landgrave, William Gary",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Myrtle Beach - Baseball Nationals",
    "month": "JUNE",
    "startDate": "20th",
    "endDate": "26th",
    "status": "LOCKED IN",
    "state": "SC",
    "crewNeeded": "2",
    "crew": "Maddox, CARTER WILLIAMS",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Broken Bow World Series",
    "month": "JUNE",
    "startDate": "19th",
    "endDate": "22nd",
    "status": "LOCKED IN",
    "state": "OK",
    "crewNeeded": "3-4",
    "crew": "Will Fox, PJ, Tyler Collins",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Youth World Series - Ozarks",
    "month": "JUNE",
    "startDate": "18th",
    "endDate": "22nd",
    "status": "LOCKED IN",
    "state": "MO",
    "crewNeeded": "2",
    "crew": "CHRIS PEYTON, Cody Lyons",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Grand Slam Classic",
    "month": "JUNE",
    "startDate": "21st",
    "endDate": "22nd",
    "status": "LOCKED IN",
    "state": "IN",
    "crewNeeded": "2",
    "crew": "vernon, Landri",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "USSA LA Arrowhead World Series Turf",
    "month": "JUNE",
    "startDate": "19th",
    "endDate": "22nd",
    "status": "LOCKED IN",
    "state": "AL",
    "crewNeeded": "3",
    "crew": "Caleb Alexander, Aubri",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Matt Hamilton 250 Teamer",
    "month": "JUNE",
    "startDate": "19th",
    "endDate": "22nd",
    "status": "LOCKED IN",
    "state": "AL",
    "crewNeeded": "3",
    "crew": "Bryce Cousin, Hudson, Eli Alviso",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "Blue Sox Bash Tournament",
    "month": "JUNE",
    "startDate": "20th",
    "endDate": "22nd",
    "status": "LOCKED IN",
    "state": "MN",
    "crewNeeded": "2",
    "crew": "JoJo Breeland, Chase Butler",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "",
    "month": "",
    "startDate": "",
    "endDate": "",
    "status": "",
    "state": "",
    "crewNeeded": "",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "",
    "month": "",
    "startDate": "",
    "endDate": "",
    "status": "",
    "state": "",
    "crewNeeded": "",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "",
    "month": "",
    "startDate": "",
    "endDate": "",
    "status": "",
    "state": "",
    "crewNeeded": "",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "",
    "month": "",
    "startDate": "",
    "endDate": "",
    "status": "",
    "state": "",
    "crewNeeded": "",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "",
    "month": "",
    "startDate": "",
    "endDate": "",
    "status": "",
    "state": "",
    "crewNeeded": "",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "",
    "month": "",
    "startDate": "",
    "endDate": "",
    "status": "",
    "state": "",
    "crewNeeded": "",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Soccer",
    "name": "",
    "month": "",
    "startDate": "",
    "endDate": "",
    "status": "",
    "state": "",
    "crewNeeded": "",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "",
    "month": "",
    "startDate": "",
    "endDate": "",
    "status": "",
    "state": "",
    "crewNeeded": "",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "",
    "month": "",
    "startDate": "",
    "endDate": "",
    "status": "",
    "state": "",
    "crewNeeded": "",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "",
    "month": "",
    "startDate": "",
    "endDate": "",
    "status": "",
    "state": "",
    "crewNeeded": "",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "",
    "month": "",
    "startDate": "",
    "endDate": "",
    "status": "",
    "state": "",
    "crewNeeded": "",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "",
    "month": "",
    "startDate": "",
    "endDate": "",
    "status": "",
    "state": "",
    "crewNeeded": "",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "",
    "month": "",
    "startDate": "",
    "endDate": "",
    "status": "",
    "state": "",
    "crewNeeded": "",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "",
    "month": "",
    "startDate": "",
    "endDate": "",
    "status": "",
    "state": "",
    "crewNeeded": "",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "",
    "month": "",
    "startDate": "",
    "endDate": "",
    "status": "",
    "state": "",
    "crewNeeded": "",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "",
    "month": "",
    "startDate": "",
    "endDate": "",
    "status": "",
    "state": "",
    "crewNeeded": "",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "",
    "month": "",
    "startDate": "",
    "endDate": "",
    "status": "",
    "state": "",
    "crewNeeded": "",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  },
  {
    "sport": "Baseball",
    "name": "",
    "month": "",
    "startDate": "",
    "endDate": "",
    "status": "",
    "state": "",
    "crewNeeded": "",
    "crew": "",
    "pexCard": "",
    "leaveDate": "",
    "leaveTime": "",
    "rentalReturn": "",
    "leaveTimesSent": "",
    "pexQuestion": ""
  }
];