services:
  - type: web
    name: fs-sports-merch-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0