const SOCCER_PACKING = {
  "sizes": {
    "16-xxs": {
      "Total Jerseys": 0
    },
    "18-xs": {
      "Total Jerseys": 0
    },
    "20-s": {
      "Messi Special": 26,
      "Ronaldo Blue": 50,
      "Ronaldo Red": 13,
      "Ronaldo White": 16,
      "Ronaldo Special": 10,
      "France Mbappe": 6,
      "Yamal Special": 0,
      "Yamal Black": 11,
      "Yamal Barca": 18,
      "Neymar Yellow": 29,
      "Pulisic AC Milan": 11,
      "Yamal Kobe": 13,
      "Yamal Pink": 10,
      "Yamal Flower": 10,
      "Messi PSG": 12,
      "Messi Tribute": 0,
      "Neymar Tribute": 40,
      "Yamal Snake": 11,
      "Gimenez": 0,
      "Ronaldo WC": 46,
      "Total Jerseys": 332
    },
    "22-m": {
      "Messi Special": 137,
      "Ronaldo Blue": 55,
      "Ronaldo Red": 19,
      "Ronaldo White": 46,
      "Ronaldo Special": 15,
      "France Mbappe": 22,
      "Yamal Special": 5,
      "Yamal Black": 40,
      "Yamal Barca": 36,
      "Neymar Yellow": 39,
      "Pulisic AC Milan": 16,
      "Yamal Kobe": 62,
      "Yamal Pink": 26,
      "Yamal Flower": 22,
      "Messi PSG": 27,
      "Messi Tribute": 19,
      "Neymar Tribute": 103,
      "Yamal Snake": 27,
      "Gimenez": 19,
      "Ronaldo WC": 53,
      "Total Jerseys": 788
    },
    "24-l": {
      "Messi Special": 35,
      "Ronaldo Blue": 59,
      "Ronaldo Red": 38,
      "Ronaldo White": 42,
      "Ronaldo Special": 76,
      "France Mbappe": 12,
      "Yamal Special": 0,
      "Yamal Black": 37,
      "Yamal Barca": 65,
      "Neymar Yellow": 55,
      "Pulisic AC Milan": 23,
      "Yamal Kobe": 34,
      "Yamal Pink": 42,
      "Yamal Flower": 103,
      "Messi PSG": 34,
      "Messi Tribute": 4,
      "Neymar Tribute": 38,
      "Yamal Snake": 53,
      "Gimenez": 30,
      "Ronaldo WC": 51,
      "Total Jerseys": 831
    },
    "26-xl": {
      "Messi Special": 26,
      "Ronaldo Blue": 57,
      "Ronaldo Red": 62,
      "Ronaldo White": 63,
      "Ronaldo Special": 88,
      "France Mbappe": 3,
      "Yamal Special": 6,
      "Yamal Black": 49,
      "Yamal Barca": 70,
      "Neymar Yellow": 74,
      "Pulisic AC Milan": 11,
      "Yamal Kobe": 40,
      "Yamal Pink": 13,
      "Yamal Flower": 121,
      "Messi PSG": 43,
      "Messi Tribute": 12,
      "Neymar Tribute": 51,
      "Yamal Snake": 46,
      "Gimenez": 35,
      "Ronaldo WC": 67,
      "Total Jerseys": 937
    },
    "28-xxl": {
      "Messi Special": 138,
      "Ronaldo Blue": 73,
      "Ronaldo Red": 83,
      "Ronaldo White": 54,
      "Ronaldo Special": 127,
      "France Mbappe": 0,
      "Yamal Special": 3,
      "Yamal Black": 53,
      "Yamal Barca": 38,
      "Neymar Yellow": 72,
      "Pulisic AC Milan": 9,
      "Yamal Kobe": 35,
      "Yamal Pink": 16,
      "Yamal Flower": 27,
      "Messi PSG": 52,
      "Messi Tribute": 31,
      "Neymar Tribute": 58,
      "Yamal Snake": 30,
      "Gimenez": 49,
      "Ronaldo WC": 108,
      "Total Jerseys": 1056
    },
    "S": {
      "Messi Special": 119,
      "Ronaldo Blue": 61,
      "Ronaldo Red": 82,
      "Ronaldo White": 40,
      "Ronaldo Special": 29,
      "France Mbappe": 2,
      "Yamal Special": 8,
      "Yamal Black": 20,
      "Yamal Barca": 60,
      "Neymar Yellow": 13,
      "Pulisic AC Milan": 11,
      "Yamal Kobe": 61,
      "Yamal Pink": 58,
      "Yamal Flower": 47,
      "Messi PSG": 34,
      "Messi Tribute": 26,
      "Neymar Tribute": 67,
      "Yamal Snake": 36,
      "Gimenez": 15,
      "Ronaldo WC": 68,
      "Total Jerseys": 857
    },
    "M": {
      "Messi Special": 99,
      "Ronaldo Blue": 71,
      "Ronaldo Red": 46,
      "Ronaldo White": 42,
      "Ronaldo Special": 62,
      "France Mbappe": 15,
      "Yamal Special": 5,
      "Yamal Black": 14,
      "Yamal Barca": 52,
      "Neymar Yellow": -5,
      "Pulisic AC Milan": 5,
      "Yamal Kobe": 25,
      "Yamal Pink": 34,
      "Yamal Flower": 38,
      "Messi PSG": 33,
      "Messi Tribute": 26,
      "Neymar Tribute": 104,
      "Yamal Snake": 40,
      "Gimenez": 16,
      "Ronaldo WC": 44,
      "Total Jerseys": 766
    },
    "L": {
      "Messi Special": 100,
      "Ronaldo Blue": 54,
      "Ronaldo Red": 32,
      "Ronaldo White": 41,
      "Ronaldo Special": 60,
      "France Mbappe": 11,
      "Yamal Special": 19,
      "Yamal Black": 40,
      "Yamal Barca": 44,
      "Neymar Yellow": 7,
      "Pulisic AC Milan": 10,
      "Yamal Kobe": 55,
      "Yamal Pink": 67,
      "Yamal Flower": 41,
      "Messi PSG": 23,
      "Messi Tribute": 18,
      "Neymar Tribute": 117,
      "Yamal Snake": 44,
      "Gimenez": 13,
      "Ronaldo WC": 40,
      "Total Jerseys": 836
    },
    "XL": {
      "Messi Special": 43,
      "Ronaldo Blue": 26,
      "Ronaldo Red": 18,
      "Ronaldo White": 38,
      "Ronaldo Special": 44,
      "France Mbappe": 8,
      "Yamal Special": 20,
      "Yamal Black": 40,
      "Yamal Barca": 27,
      "Neymar Yellow": 12,
      "Pulisic AC Milan": 6,
      "Yamal Kobe": 45,
      "Yamal Pink": 64,
      "Yamal Flower": 20,
      "Messi PSG": 22,
      "Messi Tribute": 11,
      "Neymar Tribute": 87,
      "Yamal Snake": 27,
      "Gimenez": 8,
      "Ronaldo WC": 7,
      "Total Jerseys": 573
    },
    "SIZE": {}
  },
  "totals": {
    "Total Jerseys": 6976,
    "Messi Special": 723,
    "Ronaldo Blue": 506,
    "Ronaldo Red": 393,
    "Ronaldo White": 382,
    "Ronaldo Special": 511,
    "France Mbappe": 79,
    "Yamal Special": 66,
    "Yamal Black": 304,
    "Yamal Barca": 410,
    "Neymar Yellow": 296,
    "Pulisic AC Milan": 102,
    "Yamal Kobe": 370,
    "Yamal Pink": 330,
    "Yamal Flower": 429,
    "Messi PSG": 280,
    "Messi Tribute": 147,
    "Neymar Tribute": 665,
    "Yamal Snake": 314,
    "Gimenez": 185,
    "Ronaldo WC": 484
  },
  "jerseyNames": [
    "Messi Special",
    "Ronaldo Blue",
    "Ronaldo Red",
    "Ronaldo White",
    "Ronaldo Special",
    "France Mbappe",
    "Yamal Special",
    "Yamal Black",
    "Yamal Barca",
    "Neymar Yellow",
    "Pulisic AC Milan",
    "Yamal Kobe",
    "Yamal Pink",
    "Yamal Flower",
    "Messi PSG",
    "Messi Tribute",
    "Neymar Tribute",
    "Yamal Snake",
    "Gimenez",
    "Ronaldo WC",
    "Blue Neymar",
    "Messi Black",
    "Messi Pink",
    "Messi Argentina",
    "Messi Aqua",
    "Messi Easter",
    "Vini Jr",
    "Yamal Spain",
    "Total Jerseys"
  ]
};
