const TOURNEY_DATA = [
  {
    "name": "2024 Colleen Reilly Tournament",
    "ageGroup": "",
    "month": "Aug 16-18",
    "size": "130",
    "state": "PA",
    "sport": "Soccer",
    "sites": "4",
    "setups": "",
    "responsible": "",
    "contact": "csachson@horshamsoccer.com"
  },
  {
    "name": "Community Kickoff",
    "ageGroup": "",
    "month": "Aug 16-18",
    "size": "130",
    "state": "KY",
    "sport": "Soccer",
    "sites": "1",
    "setups": "",
    "responsible": "",
    "contact": ""
  },
  {
    "name": "Bolingbrook Labor Day Festival",
    "ageGroup": "",
    "month": "Aug 30- Sept 1",
    "size": "134",
    "state": "IL",
    "sport": "Soccer",
    "sites": "2",
    "setups": "",
    "responsible": "",
    "contact": "Brooke.stobaugh@bolingbrooksoccerclub.org"
  },
  {
    "name": "Texas Labor Day Cup",
    "ageGroup": "",
    "month": "Aug 31st-Sept 2nd",
    "size": "320",
    "state": "TX",
    "sport": "Soccer",
    "sites": "2",
    "setups": "",
    "responsible": "",
    "contact": "Maria@texassportsgroup.com"
  },
  {
    "name": "Labor Day Kick-Off Classic",
    "ageGroup": "",
    "month": "Aug 31st",
    "size": "74",
    "state": "OK",
    "sport": "Soccer",
    "sites": "1",
    "setups": "",
    "responsible": "",
    "contact": "info@basoccer.club"
  },
  {
    "name": "Cajun Classic",
    "ageGroup": "",
    "month": "Sept  6-8",
    "size": "113",
    "state": "LA",
    "sport": "Soccer",
    "sites": "1 (27 fields)",
    "setups": "",
    "responsible": "",
    "contact": "cahmed@rushsoccer.com <cahmed@rushsoccer.com>"
  },
  {
    "name": "Queen City Cup",
    "ageGroup": "",
    "month": "Sept  6-8",
    "size": "122",
    "state": "OH",
    "sport": "Soccer",
    "sites": "1 (20 fields)",
    "setups": "",
    "responsible": "",
    "contact": "cahmed@rushsoccer.com <cahmed@rushsoccer.com>"
  },
  {
    "name": "FC Alliance North Fall Classic",
    "ageGroup": "",
    "month": "Sept. 7-8",
    "size": "37",
    "state": "TN",
    "sport": "Soccer",
    "sites": "1",
    "setups": "",
    "responsible": "",
    "contact": ""
  },
  {
    "name": "1ST Annual Quad City Fall Shootout",
    "ageGroup": "",
    "month": "September 13-15",
    "size": "87",
    "state": "IL",
    "sport": "Soccer",
    "sites": "1",
    "setups": "",
    "responsible": "",
    "contact": "tournament@emssc.org"
  },
  {
    "name": "Montana Surf Challenge",
    "ageGroup": "",
    "month": "September 14-15",
    "size": "115",
    "state": "MT",
    "sport": "Soccer",
    "sites": "2",
    "setups": "",
    "responsible": "",
    "contact": "Montanasurfchallenge@gmail.com (Erin)"
  },
  {
    "name": "Give N Go Charity Tournament",
    "ageGroup": "",
    "month": "Sept 20-22",
    "size": "120",
    "state": "IL",
    "sport": "Soccer",
    "sites": "1",
    "setups": "",
    "responsible": "",
    "contact": "tournament@synergysoccerclub.com"
  },
  {
    "name": "2024 Black Hills Cup",
    "ageGroup": "",
    "month": "Sept 20-22",
    "size": "90",
    "state": "SD",
    "sport": "Soccer",
    "sites": "1",
    "setups": "",
    "responsible": "",
    "contact": "sturgissoccer@hotmail.com"
  },
  {
    "name": "Wisconsin Rush OctoberFest",
    "ageGroup": "",
    "month": "Sep. 27-29",
    "size": "60",
    "state": "WI",
    "sport": "Soccer",
    "sites": "1",
    "setups": "",
    "responsible": "",
    "contact": "cahmed@rushsoccer.com"
  },
  {
    "name": "IFC Fall Cup",
    "ageGroup": "",
    "month": "Sept 28-29",
    "size": "106",
    "state": "IL",
    "sport": "Soccer",
    "sites": "1",
    "setups": "",
    "responsible": "",
    "contact": "phackman9@gmail.com"
  },
  {
    "name": "The 2024 Derby",
    "ageGroup": "",
    "month": "Sep. 27-29",
    "size": "144",
    "state": "AZ",
    "sport": "Soccer",
    "sites": "2",
    "setups": "",
    "responsible": "",
    "contact": "Aly.moon@legendsfc.net"
  },
  {
    "name": "MS River Derby",
    "ageGroup": "",
    "month": "Sep 28-29",
    "size": "29",
    "state": "MO",
    "sport": "Soccer",
    "sites": "1",
    "setups": "",
    "responsible": "",
    "contact": ""
  },
  {
    "name": "United Futbol Cup 2024",
    "ageGroup": "",
    "month": "Oct. 5-6",
    "size": "158",
    "state": "OH",
    "sport": "Soccer",
    "sites": "1",
    "setups": "2",
    "responsible": "",
    "contact": "barcelonaunitedsc@gmail.com"
  },
  {
    "name": "Spring Creek Iowa Fall Classic",
    "ageGroup": "",
    "month": "Oct. 5-6",
    "size": "73",
    "state": "IA",
    "sport": "Soccer",
    "sites": "1",
    "setups": "2",
    "responsible": "",
    "contact": "dcousineau@kingshammersbd.com"
  },
  {
    "name": "OLOL",
    "ageGroup": "",
    "month": "Oct. 5-6",
    "size": "209",
    "state": "LA",
    "sport": "Soccer",
    "sites": "1",
    "setups": "1",
    "responsible": "",
    "contact": "pfletcher@brsoccer.org"
  },
  {
    "name": "Glacier Surf Premier Cup",
    "ageGroup": "",
    "month": "Oct. 4-6",
    "size": "90",
    "state": "MT",
    "sport": "Soccer",
    "sites": "2",
    "setups": "2",
    "responsible": "",
    "contact": "nate@glaciersurfsoccer.com"
  },
  {
    "name": "Scottsdale Cup",
    "ageGroup": "YES",
    "month": "Oct 11-13",
    "size": "241",
    "state": "AZ",
    "sport": "Soccer",
    "sites": "2",
    "setups": "2",
    "responsible": "",
    "contact": "Rated Sports"
  },
  {
    "name": "NC Rush Triad Fall Classic",
    "ageGroup": "YES",
    "month": "Oct 12-13",
    "size": "33",
    "state": "NC",
    "sport": "Soccer",
    "sites": "1",
    "setups": "1",
    "responsible": "",
    "contact": "cahmed@rushsoccer.com <cahmed@rushsoccer.com>"
  },
  {
    "name": "Norski SC Fall Bash",
    "ageGroup": "",
    "month": "Oct 11-13",
    "size": "87",
    "state": "WI",
    "sport": "Soccer",
    "sites": "1",
    "setups": "1",
    "responsible": "",
    "contact": "norskisctournamentdirector@gmail.com"
  },
  {
    "name": "CDO Southwest Showdown",
    "ageGroup": "YES",
    "month": "October 18th-20th",
    "size": "100",
    "state": "AZ",
    "sport": "Soccer",
    "sites": "1",
    "setups": "1",
    "responsible": "",
    "contact": "cdotournaments@gmail.com"
  },
  {
    "name": "Monster Mash at Cherry Island",
    "ageGroup": "",
    "month": "Oct. 19th",
    "size": "99",
    "state": "CA",
    "sport": "Soccer",
    "sites": "1",
    "setups": "1",
    "responsible": "",
    "contact": "jctournament@aol.com"
  },
  {
    "name": "Kick or Treat",
    "ageGroup": "",
    "month": "Oct 18-20",
    "size": "40",
    "state": "OK",
    "sport": "Soccer",
    "sites": "1",
    "setups": "1",
    "responsible": "",
    "contact": "VP@lawtonsoccerclub.org"
  },
  {
    "name": "Southeast Classic at Gatlinburg",
    "ageGroup": "",
    "month": "Oct 19-20",
    "size": "106",
    "state": "TN",
    "sport": "Soccer",
    "sites": "1",
    "setups": "1",
    "responsible": "",
    "contact": "soccercam1019@gmail.com"
  },
  {
    "name": "Haunted Capital Cup",
    "ageGroup": "",
    "month": "October 25-27",
    "size": "55",
    "state": "MO",
    "sport": "Soccer",
    "sites": "1",
    "setups": "1",
    "responsible": "",
    "contact": "tchapman.uccsoccer@outlook.com"
  },
  {
    "name": "ELK GROVE Ghoust Games",
    "ageGroup": "",
    "month": "October 25-27",
    "size": "284",
    "state": "CA",
    "sport": "Soccer",
    "sites": "3",
    "setups": "3",
    "responsible": "",
    "contact": "hkhangura@elkgrovesoccer.com"
  },
  {
    "name": "Colorado East Cup",
    "ageGroup": "",
    "month": "Nov 1-3",
    "size": "144",
    "state": "CO",
    "sport": "Soccer",
    "sites": "2",
    "setups": "2",
    "responsible": "",
    "contact": "cahmed@rushsoccer.com <cahmed@rushsoccer.com>"
  },
  {
    "name": "Arsenal Cup",
    "ageGroup": "",
    "month": "Nov 9-10",
    "size": "105",
    "state": "GA",
    "sport": "Soccer",
    "sites": "1",
    "setups": "1",
    "responsible": "",
    "contact": "llevesque@ymcarome.org"
  },
  {
    "name": "Gatlinburg College Showcase (U14-19)",
    "ageGroup": "",
    "month": "Nov 9-10",
    "size": "80",
    "state": "TN",
    "sport": "Soccer",
    "sites": "1",
    "setups": "1",
    "responsible": "",
    "contact": "soccercam1019@gmail.com"
  },
  {
    "name": "2024 DSA 30th Annual Invitational",
    "ageGroup": "",
    "month": "Nov 8-10",
    "size": "100",
    "state": "TX",
    "sport": "Soccer",
    "sites": "1",
    "setups": "1",
    "responsible": "",
    "contact": ""
  },
  {
    "name": "Impact Premier Cup",
    "ageGroup": "u8-u19",
    "month": "Nov 16-17",
    "size": "228",
    "state": "GA",
    "sport": "Soccer",
    "sites": "2",
    "setups": "2",
    "responsible": "",
    "contact": "soccercam1019@gmail.com"
  },
  {
    "name": "Adidas Clash",
    "ageGroup": "u9-u19",
    "month": "Nov 15-17",
    "size": "170",
    "state": "NC",
    "sport": "Soccer",
    "sites": "2",
    "setups": "2",
    "responsible": "",
    "contact": "Ggartner@ncfusion.org"
  },
  {
    "name": "Rocky Mountain Fall Championship",
    "ageGroup": "u9-u10",
    "month": "Nov 16-17",
    "size": "92",
    "state": "CO",
    "sport": "Soccer",
    "sites": "1",
    "setups": "2",
    "responsible": "",
    "contact": "randy.weber@rapidsyouthsoccer.org"
  },
  {
    "name": "Fall Classic",
    "ageGroup": "u4-u18",
    "month": "Nov 15-17",
    "size": "65",
    "state": "TX",
    "sport": "Soccer",
    "sites": "1",
    "setups": "1",
    "responsible": "",
    "contact": "isatournamentdirector@gmail.com"
  },
  {
    "name": "Mountain State Cup",
    "ageGroup": "Yes//  u7-u19",
    "month": "Nov 15-17",
    "size": "140",
    "state": "WV",
    "sport": "Soccer",
    "sites": "1",
    "setups": "1",
    "responsible": "",
    "contact": "Samantha@shawneesports.com"
  },
  {
    "name": "Bullhead City Baseball: Thanksgiving Classic",
    "ageGroup": "u8-u18",
    "month": "Nov 15-17",
    "size": "35",
    "state": "AZ",
    "sport": "Baseball",
    "sites": "2",
    "setups": "1",
    "responsible": "",
    "contact": "702-969-1727"
  },
  {
    "name": "West-Mont Fall Finale",
    "ageGroup": "u8-u14",
    "month": "Nov 22-24",
    "size": "65",
    "state": "PA",
    "sport": "Soccer",
    "sites": "1",
    "setups": "",
    "responsible": "",
    "contact": "moplinger@westmontunitedsoccer.org"
  },
  {
    "name": "Thanksgiving Classic",
    "ageGroup": "U7-U19",
    "month": "Nov 23-24",
    "size": "30",
    "state": "CA",
    "sport": "Soccer",
    "sites": "1",
    "setups": "",
    "responsible": "JR",
    "contact": "626-319-8480"
  },
  {
    "name": "LTE Fall Classic",
    "ageGroup": "U7-U16",
    "month": "Nov 23-24",
    "size": "110",
    "state": "TX",
    "sport": "Soccer",
    "sites": "2",
    "setups": "2",
    "responsible": "Wes",
    "contact": "andy@ltesoccer.com"
  },
  {
    "name": "Hawaii Thanksgiving INV",
    "ageGroup": "U8-U15",
    "month": "Nov 29-Dec 1",
    "size": "125",
    "state": "Hawaii",
    "sport": "Soccer",
    "sites": "1",
    "setups": "1",
    "responsible": "Lane",
    "contact": "cahmed@rushsoccer.com <cahmed@rushsoccer.com>"
  },
  {
    "name": "Desert Supercup",
    "ageGroup": "U9-U14",
    "month": "Nov 29-Dec 1",
    "size": "196",
    "state": "AZ",
    "sport": "Soccer",
    "sites": "2",
    "setups": "2",
    "responsible": "Lane",
    "contact": "tarapielaet@ratedsports.com"
  },
  {
    "name": "1. La jolla All Star",
    "ageGroup": "U8-U14",
    "month": "Dec. 7-8",
    "size": "75",
    "state": "CA",
    "sport": "Soccer",
    "sites": "2",
    "setups": "2",
    "responsible": "JR",
    "contact": "anthony@stspecialists.com"
  },
  {
    "name": "2. Cornado Holiday Cup",
    "ageGroup": "U8-U14",
    "month": "Dec. 7-8",
    "size": "75",
    "state": "CA",
    "sport": "Soccer",
    "sites": "1 Tidelands Park",
    "setups": "1",
    "responsible": "JR",
    "contact": "anthony@stspecialists.com"
  },
  {
    "name": "3. Atlantic Cup",
    "ageGroup": "U9-U19",
    "month": "Dec 7-8",
    "size": "100",
    "state": "VA",
    "sport": "Soccer",
    "sites": "1",
    "setups": "1",
    "responsible": "Lane",
    "contact": "cahmed@rushsoccer.com <cahmed@rushsoccer.com>"
  },
  {
    "name": "4. The Open",
    "ageGroup": "U8-U14",
    "month": "Dec 6-8  EARLY FRIDAY",
    "size": "115",
    "state": "AZ",
    "sport": "Soccer",
    "sites": "2//// Reata U12-U15//// Bell94 U9-U12",
    "setups": "2",
    "responsible": "Lane",
    "contact": "aly.moon@legendsfc.net"
  },
  {
    "name": "5. Gatlinburg Season Finale",
    "ageGroup": "U9-U19",
    "month": "Dec 7-8",
    "size": "101",
    "state": "TN",
    "sport": "Soccer",
    "sites": "1",
    "setups": "1",
    "responsible": "Lane",
    "contact": "soccercam1019@gmail.com"
  },
  {
    "name": "6. Level Up Cup",
    "ageGroup": "u8-u19",
    "month": "Dec 7-8",
    "size": "167",
    "state": "TX",
    "sport": "Soccer",
    "sites": "1",
    "setups": "1",
    "responsible": "JR",
    "contact": "Maria@texassportsgroup.com"
  },
  {
    "name": "Homestead Cup",
    "ageGroup": "U8-U16",
    "month": "Dec 14-15",
    "size": "45",
    "state": "FL",
    "sport": "Soccer",
    "sites": "2// Loren Roberts - Olders// Miami Communiuty - youngers",
    "setups": "2",
    "responsible": "WES",
    "contact": "mayowa.owolabi@iepsoccer.com"
  },
  {
    "name": "Lafayette Market",
    "ageGroup": "NA",
    "month": "DEC 14-15",
    "size": "100",
    "state": "LA",
    "sport": "NA",
    "sites": "1",
    "setups": "1",
    "responsible": "Lane",
    "contact": ""
  },
  {
    "name": "Illinois Futsal",
    "ageGroup": "",
    "month": "Dec 21-22",
    "size": "30",
    "state": "IL",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": ""
  },
  {
    "name": "Futsal Illinois State Championship",
    "ageGroup": "U8-U19",
    "month": "Dec 20-22",
    "size": "47",
    "state": "IL",
    "sport": "Soccer",
    "sites": "1",
    "setups": "1",
    "responsible": "Wes",
    "contact": "630-447-8384"
  },
  {
    "name": "HI-5 Tournament",
    "ageGroup": "",
    "month": "Jan 4-5",
    "size": "72",
    "state": "CA",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "Lane",
    "contact": "Michael Ramirez <ayso5rc@gmail.com>"
  },
  {
    "name": "Winter Thunder Cup",
    "ageGroup": "U9-U13",
    "month": "Jan 11-12",
    "size": "65",
    "state": "CA",
    "sport": "Soccer",
    "sites": "1",
    "setups": "1",
    "responsible": "JR",
    "contact": "anthony@stspecialists.com"
  },
  {
    "name": "Sol Winter Classic",
    "ageGroup": "U8-U12",
    "month": "Jan 11-12",
    "size": "37",
    "state": "CA",
    "sport": "Soccer",
    "sites": "2/ Sequoia Elem & Innovation MS",
    "setups": "2",
    "responsible": "Lane",
    "contact": "sanmarcosunited@gmail.com  (Janet)"
  },
  {
    "name": "Rated Cup",
    "ageGroup": "U7-U19",
    "month": "Jan 18-19",
    "size": "72",
    "state": "AZ",
    "sport": "Soccer",
    "sites": "1",
    "setups": "1",
    "responsible": "Lane",
    "contact": "tarapielaet@ratedsports.com"
  },
  {
    "name": "Vegas Cup",
    "ageGroup": "",
    "month": "Jan 17-20",
    "size": "450",
    "state": "NV",
    "sport": "Soccer",
    "sites": "1",
    "setups": "2",
    "responsible": "Lane/Wes",
    "contact": ""
  },
  {
    "name": "Colorado Futsal Championships",
    "ageGroup": "",
    "month": "Jan 24-26",
    "size": "85",
    "state": "CO",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "Lane",
    "contact": "randy.weber@rapidsyouthsoccer.org"
  },
  {
    "name": "Winter Cold Snap (One Day)",
    "ageGroup": "U7-U15",
    "month": "Jan 25",
    "size": "45",
    "state": "TX",
    "sport": "Soccer",
    "sites": "1",
    "setups": "1",
    "responsible": "JR",
    "contact": "469 583 3160"
  },
  {
    "name": "Lexington SA Cup",
    "ageGroup": "U8-U14",
    "month": "Feb 1-2",
    "size": "136",
    "state": "SC",
    "sport": "Soccer",
    "sites": "1",
    "setups": "2",
    "responsible": "Lane",
    "contact": "nicholbs@yahoo.com"
  },
  {
    "name": "Academy World Cup Friendlies",
    "ageGroup": "U9-U10",
    "month": "Feb 8-9",
    "size": "32",
    "state": "TX",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "Wes",
    "contact": ""
  },
  {
    "name": "MYSA Spring Shootout",
    "ageGroup": "U7-U19",
    "month": "Feb 8-9",
    "size": "125",
    "state": "NC",
    "sport": "Soccer",
    "sites": "2",
    "setups": "2",
    "responsible": "Ryan",
    "contact": ""
  },
  {
    "name": "2025 Cal North Junior Cup",
    "ageGroup": "U9-U12",
    "month": "Feb 15-16",
    "size": "60",
    "state": "CA",
    "sport": "Soccer",
    "sites": "1",
    "setups": "",
    "responsible": "Wes",
    "contact": "ddenkers@calnorth.org"
  },
  {
    "name": "Icebreaker 2025",
    "ageGroup": "",
    "month": "Feb 15-17",
    "size": "210",
    "state": "UT",
    "sport": "Soccer",
    "sites": "1",
    "setups": "1",
    "responsible": "Wes",
    "contact": "icebreakersoccer@gmail.com"
  },
  {
    "name": "Elk Grove Spring Kickoff Classic",
    "ageGroup": "",
    "month": "Feb 15-16",
    "size": "",
    "state": "CA",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "JR",
    "contact": "hkhangura@elkgrovesoccer.com"
  },
  {
    "name": "Power Ford Rio Rapids Cup",
    "ageGroup": "U9-U19",
    "month": "Feb 15-16",
    "size": "100",
    "state": "NM",
    "sport": "Soccer",
    "sites": "1",
    "setups": "1",
    "responsible": "Lane",
    "contact": "yancey.ranspot@riorapids.org"
  },
  {
    "name": "Central USSSA",
    "ageGroup": "",
    "month": "Feb 22-23",
    "size": "",
    "state": "LA",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "JR",
    "contact": "brannon.danos33@gmail.com"
  },
  {
    "name": "Winter Wind Up Grand Slam",
    "ageGroup": "U7-U13",
    "month": "Feb 21-22",
    "size": "20-30",
    "state": "LA",
    "sport": "Baseball",
    "sites": "1",
    "setups": "",
    "responsible": "Ryan",
    "contact": "Jody - (318) 669-9077"
  },
  {
    "name": "28th Annual Sun belt classic",
    "ageGroup": "",
    "month": "Feb 22-23",
    "size": "",
    "state": "CO",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "Wes/Lane",
    "contact": "Jenniferlgrable@gmail.com"
  },
  {
    "name": "Castro Valley Spring Classic",
    "ageGroup": "u8-u12",
    "month": "Feb 22-23",
    "size": "130-150",
    "state": "CA",
    "sport": "Soccer",
    "sites": "3",
    "setups": "3",
    "responsible": "Wes",
    "contact": "vicepresident@castrovalleysoccer.com"
  },
  {
    "name": "Shamrock Shakedown",
    "ageGroup": "",
    "month": "March 1-2",
    "size": "",
    "state": "AZ",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "JR",
    "contact": "702-969-1727"
  },
  {
    "name": "East Coast Spring Shootout (VA Rush)",
    "ageGroup": "",
    "month": "March 7-9",
    "size": "",
    "state": "VA",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "Lane",
    "contact": "Chris Ahmed <cahmed@rushsoccer.com>"
  },
  {
    "name": "Red Stick Tournament",
    "ageGroup": "u10-u19",
    "month": "March 6-9",
    "size": "",
    "state": "LA",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "JR",
    "contact": "pfletcher@brsoccer.org"
  },
  {
    "name": "Premier Cup",
    "ageGroup": "u7-u19",
    "month": "March 8-9",
    "size": "",
    "state": "TX",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "Wes",
    "contact": "AUSTIN@TIGERTOURNAMENTS.COM"
  },
  {
    "name": "Parish Line USSSA",
    "ageGroup": "",
    "month": "March 8-9",
    "size": "",
    "state": "LA",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "JR",
    "contact": "brannon.danos33@gmail.com"
  },
  {
    "name": "Springfest 2025",
    "ageGroup": "",
    "month": "March 8-9",
    "size": "",
    "state": "CA",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "JR",
    "contact": "Miguel"
  },
  {
    "name": "Live Oak USSSA",
    "ageGroup": "",
    "month": "March 15-16",
    "size": "",
    "state": "LA",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "JR",
    "contact": "brannon.danos33@gmail.com"
  },
  {
    "name": "Courtesy Cajun Lagniappe (LA Crew)",
    "ageGroup": "",
    "month": "March 14-16",
    "size": "",
    "state": "LA",
    "sport": "Socccer",
    "sites": "",
    "setups": "",
    "responsible": "Lane",
    "contact": "Chris Ahmed <cahmed@rushsoccer.com>"
  },
  {
    "name": "Spring Madness Showcase",
    "ageGroup": "u7-u19",
    "month": "March 15-16",
    "size": "",
    "state": "CA",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "JR",
    "contact": "Marina: 951-760-9914"
  },
  {
    "name": "St. Patrick's Show Down Grand Slam",
    "ageGroup": "U7-U12",
    "month": "March 14-15",
    "size": "20-30",
    "state": "LA",
    "sport": "Baseball",
    "sites": "1",
    "setups": "",
    "responsible": "Ryan",
    "contact": "Jody - (318)669-9077"
  },
  {
    "name": "Phoenix Cup - Boys",
    "ageGroup": "",
    "month": "March 21-23",
    "size": "",
    "state": "AZ",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "tarapielaet@ratedsports.com"
  },
  {
    "name": "Live Oak USSSA",
    "ageGroup": "",
    "month": "March 22-23",
    "size": "",
    "state": "LA",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "brannon.danos33@gmail.com"
  },
  {
    "name": "Cullman Showdown",
    "ageGroup": "U6-U15",
    "month": "March 22 1-day",
    "size": "50-60",
    "state": "AL",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "Ryan",
    "contact": "stebo05151983@yahoo.com"
  },
  {
    "name": "Super Slam - Turf Warz Classic ll",
    "ageGroup": "U7-U14",
    "month": "March 22-23",
    "size": "25",
    "state": "LA",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "Ryan",
    "contact": "Lofflin - (225)636-1178"
  },
  {
    "name": "TFA 4V4 Challenge (1 Day)",
    "ageGroup": "",
    "month": "March 30",
    "size": "",
    "state": "CA",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "anthony@stspecialists.com"
  },
  {
    "name": "Live Oak USSSA",
    "ageGroup": "",
    "month": "March 29-30",
    "size": "",
    "state": "LA",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "brannon.danos33@gmail.com"
  },
  {
    "name": "PSG Academy Cup",
    "ageGroup": "",
    "month": "March 28-30",
    "size": "",
    "state": "AZ",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": ""
  },
  {
    "name": "2025 GMB Rawlings Championships Series",
    "ageGroup": "",
    "month": "March 28-30",
    "size": "33",
    "state": "TN",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "Ryan/Lane",
    "contact": ""
  },
  {
    "name": "United Spring Turf Challenge",
    "ageGroup": "",
    "month": "March 29-30",
    "size": "48",
    "state": "OH",
    "sport": "Soccer",
    "sites": "1",
    "setups": "",
    "responsible": "",
    "contact": "barcelonaunitedsc@gmail.com"
  },
  {
    "name": "North Shore Preseason",
    "ageGroup": "U8-U15",
    "month": "April 4-6",
    "size": "100",
    "state": "IL",
    "sport": "Soccer",
    "sites": "1",
    "setups": "",
    "responsible": "Wes",
    "contact": "northshoretournament@jahbat.org"
  },
  {
    "name": "United Spring Turf Challenge Boys",
    "ageGroup": "",
    "month": "April 5-6",
    "size": "48",
    "state": "OH",
    "sport": "Soccer",
    "sites": "1",
    "setups": "",
    "responsible": "",
    "contact": "barcelonaunitedsc@gmail.com"
  },
  {
    "name": "Parish Line USSSA",
    "ageGroup": "",
    "month": "April 5-6",
    "size": "",
    "state": "LA",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "brannon.danos33@gmail.com"
  },
  {
    "name": "2025 GMB King of Rings",
    "ageGroup": "U9-U12",
    "month": "April 5-6",
    "size": "26",
    "state": "TN",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "Ryan/Lane",
    "contact": ""
  },
  {
    "name": "Twin City Slugfest",
    "ageGroup": "U7-U12",
    "month": "April 5-6",
    "size": "30",
    "state": "LA",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "Ryan",
    "contact": "Lofflin - (225)636-1178"
  },
  {
    "name": "NC Rush Triad Beat the Heat (NC Triad)",
    "ageGroup": "",
    "month": "April 11-13",
    "size": "",
    "state": "NC",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "Lane",
    "contact": "Chris Ahmed <cahmed@rushsoccer.com>"
  },
  {
    "name": "Live Oak USSSA",
    "ageGroup": "",
    "month": "April 11-12",
    "size": "",
    "state": "LA",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "brannon.danos33@gmail.com"
  },
  {
    "name": "Jackie Robinson",
    "ageGroup": "u7-u18",
    "month": "April 12-13",
    "size": "",
    "state": "AZ",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "702-969-1727"
  },
  {
    "name": "West Fel Turf Battle",
    "ageGroup": "U7-U12",
    "month": "April 12-13",
    "size": "15",
    "state": "LA",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "Ryan",
    "contact": "Lofflin - (225)636-1178"
  },
  {
    "name": "Smarts Early Bird Baseball Tournament",
    "ageGroup": "",
    "month": "April 19th-20th",
    "size": "",
    "state": "MI",
    "sport": "Baseball",
    "sites": "1",
    "setups": "",
    "responsible": "",
    "contact": "Brian: 734-652-8736"
  },
  {
    "name": "Texas Easter Cup",
    "ageGroup": "",
    "month": "April 19th-20th",
    "size": "",
    "state": "",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "Maria@texassportsgroup.com"
  },
  {
    "name": "Rush Select Academy Cup",
    "ageGroup": "",
    "month": "April 18th-20th",
    "size": "",
    "state": "",
    "sport": "",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": ""
  },
  {
    "name": "Copa De Sturgis",
    "ageGroup": "",
    "month": "April 19th-21st",
    "size": "",
    "state": "SD",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": ""
  },
  {
    "name": "Festival International",
    "ageGroup": "",
    "month": "April 24th -28th",
    "size": "",
    "state": "",
    "sport": "",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": ""
  },
  {
    "name": "Live Oak USSSA",
    "ageGroup": "",
    "month": "April 26-27",
    "size": "",
    "state": "LA",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "brannon.danos33@gmail.com"
  },
  {
    "name": "Wisconsin Spring Classic",
    "ageGroup": "",
    "month": "April 26-27",
    "size": "",
    "state": "WI",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "cahmed@rushsoccer.com"
  },
  {
    "name": "Autism Acceptance",
    "ageGroup": "",
    "month": "April 26-27",
    "size": "",
    "state": "AZ",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "702-969-1727"
  },
  {
    "name": "Aydin Gonulsen Memorial Tournament",
    "ageGroup": "",
    "month": "April",
    "size": "",
    "state": "",
    "sport": "",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "Ed Rose"
  },
  {
    "name": "Epic Cup",
    "ageGroup": "",
    "month": "May",
    "size": "",
    "state": "MS",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "russell@cincysc.com"
  },
  {
    "name": "Zachary Easton USSSA",
    "ageGroup": "",
    "month": "May 3-4",
    "size": "",
    "state": "LA",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "brannon.danos33@gmail.com"
  },
  {
    "name": "Norski Spring Fling Tournament",
    "ageGroup": "",
    "month": "May 2-4",
    "size": "90",
    "state": "WI",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": ""
  },
  {
    "name": "Bethesda Premier Cup TD Event",
    "ageGroup": "",
    "month": "May",
    "size": "",
    "state": "",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "240-344-4943"
  },
  {
    "name": "Mother's Day Tournament USSSA",
    "ageGroup": "",
    "month": "May 10-12",
    "size": "",
    "state": "LA",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "brannon.danos33@gmail.com"
  },
  {
    "name": "Mother's Day - Grand Slam Sports",
    "ageGroup": "U7 - U15",
    "month": "May 10-12",
    "size": "75-100",
    "state": "AL",
    "sport": "Baseball",
    "sites": "3-4",
    "setups": "",
    "responsible": "Ryan",
    "contact": "Jody - (318)669-9077"
  },
  {
    "name": "Mother's Day Grand Slam",
    "ageGroup": "U7-U12",
    "month": "May 9-10",
    "size": "20-30",
    "state": "LA",
    "sport": "Baseball",
    "sites": "1",
    "setups": "",
    "responsible": "Ryan",
    "contact": "ryan.futurestars@gmail.com"
  },
  {
    "name": "USSSA",
    "ageGroup": "",
    "month": "May 17-18",
    "size": "",
    "state": "LA",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "brannon.danos33@gmail.com"
  },
  {
    "name": "Bring the Heat",
    "ageGroup": "",
    "month": "May 17-18",
    "size": "",
    "state": "AZ",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "702-969-1727"
  },
  {
    "name": "North LA State Championship",
    "ageGroup": "U7-U14",
    "month": "May 17-18",
    "size": "32",
    "state": "LA",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "Ryan",
    "contact": "Lofflin - (225)636-1178"
  },
  {
    "name": "Nomads Spring Showdown",
    "ageGroup": "",
    "month": "May 17-18",
    "size": "",
    "state": "CA",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "JR",
    "contact": "anthony@stspecialists.com"
  },
  {
    "name": "El Clasico",
    "ageGroup": "",
    "month": "May 24-25",
    "size": "",
    "state": "UT",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "Lane",
    "contact": "cahmed@rushsoccer.com <cahmed@rushsoccer.com>"
  },
  {
    "name": "Ralph Downey Memorial Day Classic",
    "ageGroup": "",
    "month": "May 24-25",
    "size": "",
    "state": "VA",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "cahmed@rushsoccer.com <cahmed@rushsoccer.com>"
  },
  {
    "name": "Texas Super Cup",
    "ageGroup": "",
    "month": "May 24-26",
    "size": "",
    "state": "TX",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "tarapielaet@ratedsports.com"
  },
  {
    "name": "Cali Cup",
    "ageGroup": "",
    "month": "May 24-26",
    "size": "",
    "state": "CA",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "tarapielaet@ratedsports.com"
  },
  {
    "name": "Live Oak USSSA",
    "ageGroup": "",
    "month": "May 24-25",
    "size": "",
    "state": "LA",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "brannon.danos33@gmail.com"
  },
  {
    "name": "MP3 Series - South LA State Champ",
    "ageGroup": "U7-U13",
    "month": "May 31-June1",
    "size": "21",
    "state": "LA",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "Ryan",
    "contact": "Lofflin - (225)636-1178"
  },
  {
    "name": "MT State Cup",
    "ageGroup": "",
    "month": "June 6-8",
    "size": "",
    "state": "MT",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "JR",
    "contact": "president@montanarushsoccer.com"
  },
  {
    "name": "San Diego Charity Cup",
    "ageGroup": "",
    "month": "June 7-8",
    "size": "",
    "state": "CA",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "anthony@stspecialists.com"
  },
  {
    "name": "2025 GMB Fathers Day Classic",
    "ageGroup": "",
    "month": "June 13th -15th",
    "size": "",
    "state": "TN",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": ""
  },
  {
    "name": "Nomads Summer Cup",
    "ageGroup": "",
    "month": "June 21-22",
    "size": "",
    "state": "CA",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "anthony@stspecialists.com"
  },
  {
    "name": "NYC Cup",
    "ageGroup": "",
    "month": "July 11-13",
    "size": "",
    "state": "NY",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "tarapielaet@ratedsports.com"
  },
  {
    "name": "Elite Cup",
    "ageGroup": "",
    "month": "July 12-13",
    "size": "",
    "state": "CA",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "anthony@stspecialists.com"
  },
  {
    "name": "2025 GMB 8U World",
    "ageGroup": "",
    "month": "July 18th-20th",
    "size": "",
    "state": "TN",
    "sport": "Baseball",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": ""
  },
  {
    "name": "Coronado Crown City Classic",
    "ageGroup": "",
    "month": "July 26-27",
    "size": "",
    "state": "CA",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "anthony@stspecialists.com"
  },
  {
    "name": "LA Cup",
    "ageGroup": "",
    "month": "August 8-10",
    "size": "",
    "state": "CA",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "tarapielaet@ratedsports.com"
  },
  {
    "name": "El Clasico (San Antonio)",
    "ageGroup": "",
    "month": "August 15th-17th",
    "size": "",
    "state": "TX",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "cahmed@rushsoccer.com"
  },
  {
    "name": "Premier Cup",
    "ageGroup": "",
    "month": "",
    "size": "300",
    "state": "TX",
    "sport": "Soccer",
    "sites": "Reach out!!!!!!!!",
    "setups": "",
    "responsible": "",
    "contact": "Amber"
  },
  {
    "name": "La Jolla Labor Day Classic",
    "ageGroup": "",
    "month": "August 30-Sept 1",
    "size": "",
    "state": "CA",
    "sport": "Soccer",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": "anthony@stspecialists.com"
  },
  {
    "name": "MS River Derby",
    "ageGroup": "",
    "month": "September 2025",
    "size": "",
    "state": "MO",
    "sport": "",
    "sites": "",
    "setups": "",
    "responsible": "",
    "contact": ""
  }
];